Sessions overview
security-summer-school/web pull request #14
Opened 2021-07-20 11:01 UTC by antonio-macovei

I updated the sessions overview according to this year names and structure.

2021-07-20 11:49 UTC, carrrina requested changes

2021-07-20 11:49 UTC, carrrina commented on 02-access-control/README.md
> +* **Elements**: In this tab you can see the HTML structure of the page. On the right panel, you can see the styles applied to each element when selected and add, remove or edit the properties directl
This shouldn't be modified

2021-07-20 12:05 UTC, antonio-macovei commented on 02-access-control/README.md
> +* **Elements**: In this tab you can see the HTML structure of the page. On the right panel, you can see the styles applied to each element when selected and add, remove or edit the properties directl
Fixed

2021-09-02 18:43 UTC, gabrielmocanu commented
@carrrina @antonio-macovei 

What is the status of this?
When this can be merged? I saw there is a conflict, probably it will need a rebase before.

2021-09-03 11:00 UTC, carrrina requested changes

2021-09-03 11:00 UTC, carrrina commented on 09-privilege-escalation/README.md
> +# Challenges
Add a new line before this

2022-06-10 23:58 UTC, closed without merging