Add challenges and README for session 04 - SQL injection
security-summer-school/web pull request #17
Opened 2022-03-19 18:00 UTC by gabrielmocanu

Add challenges and README for session 04 - SQL injection

2022-06-15 09:14 UTC, carrrina commented
I think you made a mistake - for the challenges, only the `sol` folder (and maybe the `README.md` file) should be present in this public repo

2022-06-15 09:14 UTC, carrrina commented
I think you made a mistake - for the challenges, only the `sol` folder (and maybe the `README.md` file) should be present in this public repo

2022-06-15 09:15 UTC, carrrina requested changes

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +For example, on Oracle you could submit the input:
```suggestion
For example, in Oracle you could submit the input:
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +This uses the double-pipe sequence `||` which is a string concatenation operator on Oracle.
```suggestion
This uses the double-pipe sequence `||` which is a string concatenation operator in Oracle.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +For example, on Oracle you can execute:
```suggestion
For example, in Oracle you can execute:
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +The `SUBSTRING` function is called `SUBSTR` on some types of database.
```suggestion
The `SUBSTRING` function is called `SUBSTR` on some types of databases.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +The `SUBSTRING` function is called `SUBSTR` on some types of database.
```suggestion
The `SUBSTRING` function is called `SUBSTR` on some types of databases.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
>  Let’s look at an example and see how easy it to exploit this vulnerability.
```suggestion
Let’s look at an example and see how easy it is to exploit this vulnerability.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
>  Let’s look at an example and see how easy it to exploit this vulnerability.
```suggestion
Let’s look at an example and see how easy it is to exploit this vulnerability.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +[SQLmap](https://sqlmap.org/) is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over of database servers.
```suggestion
[SQLmap](https://sqlmap.org/) is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over database servers.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +[SQLmap](https://sqlmap.org/) is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over of database servers.
```suggestion
[SQLmap](https://sqlmap.org/) is an open source penetration testing tool that automates the process of detecting and exploiting SQL injection flaws and taking over database servers.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +  On MySQL, the double-dash sequence must be followed by a space. Alternatively, the hash character `#` can be used to identify a comment.
```suggestion
  In MySQL, the double-dash sequence must be followed by a space. Alternatively, the hash character `#` can be used to identify a comment.
```

2022-06-15 09:15 UTC, carrrina commented on sql-injection/README.md
> +  On MySQL, the double-dash sequence must be followed by a space. Alternatively, the hash character `#` can be used to identify a comment.
```suggestion
  In MySQL, the double-dash sequence must be followed by a space. Alternatively, the hash character `#` can be used to identify a comment.
```

2022-06-15 12:03 UTC, carrrina commented
All the `solution` scripts should be named `solution.sh` as per [here](https://github.com/security-summer-school/template-internal)

2022-06-24 13:56 UTC, gabrielmocanu commented
@carrrina 

Can you please look again at this PR?
I resolve all the issues you mentioned. Thanks!

2022-06-25 11:13 UTC, carrrina requested changes

2022-06-25 11:13 UTC, carrrina commented on sql-injection/README.md
> +# Other Activities
I think this line is useless, they are all activities

2022-06-25 11:13 UTC, carrrina commented
You can delete the old session and modify the repo README to point at this one

2022-06-26 13:39 UTC, gabrielmocanu commented
@carrrina 

Can you take a look again?

2022-06-26 14:17 UTC, carrrina approved these changes

2022-06-26 14:18 UTC, merged